"""Country codes and names for market selection."""

MARKETS = {
    "India": "IN",
    "United States": "US",
    "United Kingdom": "GB",
    "United Arab Emirates": "AE",
    "Saudi Arabia": "SA",
    "Germany": "DE",
    "France": "FR",
    "Singapore": "SG",
    "Australia": "AU",
    "Canada": "CA",
    "Indonesia": "ID",
    "Malaysia": "MY",
    "Thailand": "TH",
    "Philippines": "PH",
    "Vietnam": "VN",
    "Japan": "JP",
    "South Korea": "KR",
    "Brazil": "BR",
    "Mexico": "MX",
    "Nigeria": "NG",
    "South Africa": "ZA",
    "Kenya": "KE",
    "Egypt": "EG",
    "Turkey": "TR",
    "Italy": "IT",
    "Spain": "ES",
    "Netherlands": "NL",
    "Sweden": "SE",
    "Poland": "PL",
    "Pakistan": "PK",
    "Bangladesh": "BD",
    "Qatar": "QA",
    "Kuwait": "KW",
    "Bahrain": "BH",
    "Oman": "OM",
}
